// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"work/internal/biz"
	"work/internal/data"
	"work/internal/service"
)

// Injectors from wire.go:

func InitializeGreeterService() service.Greeter {
	greeter := data.NewGreeter()
	bizGreeter := biz.NewGreeter(greeter)
	serviceGreeter := service.NewGreeter(bizGreeter)
	return serviceGreeter
}
